language: cpp
sudo: required
os: linux
compiler: gcc
cache: ccache
script:
- make -j8
- mkdir $PWD/LucentCore
- sudo make install -j8
- sudo make DESTDIR=$PWD/LucentCore install -j8
- cd LucentCore/usr/local
- sudo zip -r Lucent_Core.zip .
- cd /home/travis/build/AlphaSerpentis/Lucent
before_deploy:
- lucentd --version
- lucentd --daemon
- sleep 15
- lucent-cli addnode "138.68.29.233" "add"
- sleep 120
- lucent-cli getmininginfo && lucent-cli getnetworkinfo && lucent-cli getaddednodeinfo && lucent-cli stop
before_install:
- pyenv global 3.6.7
- sudo add-apt-repository ppa:bitcoin/bitcoin -y
- sudo apt-get update
- sudo apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler
- sudo apt-get install build-essential libgl1-mesa-dev
- sudo apt-get install -y libdb4.8-dev libdb4.8++-dev
- sudo apt-get install libboost-all-dev libevent-dev
- sudo apt-get install libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev
- ./autogen.sh
- ./configure --disable-tests
deploy:
  provider: releases
  api_key:
    secure: TuQe2jCCjOsqHaWMDy6t3v5WPSXpBA4UPscWFIfUbFFo3S/zpcG6I+O+WOHZ1Lnadianheif771OnL1BxlXzwOspui45dTM3LFq+9OUwKJghWLf46KoLUjzLZ4SquvOx7oHZ2x/MXYtyfEb0DF3ENVw0jfYj8/T8IzWWViM9BO8NrsWPaHidthI6XfBLU8VFn5dkCdBQU6eKp1jLh2syzWZBbLt48XbPFP7/Dh7h8PQa5i4loNuYNPSypjwcmJGJBbSDE18fMNdhn/t0DsZ32vx8k4ttQhGX6myEc+jY5CQLunBjlwbxulraM6diqPDHy/9BTc51ce2i9yq+cYvuGCcmLWAcb6h94MVQv9l15VyEeZzmOShUIdHTCnA53BSuZYdTNjFOrMvZ45G2L956pkNXrYzyffatieIb7Fl4MwKNSDFzK4rx2Fqav9xTMtPUIjMnoqNROlPirQ3Z12iFVfNVQARSXta0xT0oDY2aKPqEtKY+KT8g6Sc1zERaWLPitPEfNtgUFa2dWjkiSUam/AVdTNvOhKUHKczqX1MsmYqVGsepQV5lHo/xhMcSbHf2HUgmu5S4h+Ly1J2kOyGYgNbj8nvzWsVSYN+RJTFgIryT4nupJJrRG6Me+PgQrhxOm2V//FZTr9PHpxIpomRQtagaZZqvETlNMf2b7T1utWE=
  file_glob: true
  file: "$PWD/LucentCore/usr/local/**"
  skip_cleanup: true
  on:
    repo: AlphaSerpentis/Lucent
    branch: develop
